library(tidyverse)

cces_2016_raw <- read_tsv("CCES/data/2016/cces_2016_raw.tab")
state_fips <- read_csv("CCES/data/state_fips.csv")

# Functions for convenience ####
binary12 <- function(x) {
  x <- case_when(x == 1 ~ TRUE,
                 x == 2 ~ FALSE)
  return(x)
}

importance <- function(x) {
  x <- case_when(x == 1 ~ "Very important",
                 x == 2 ~ "Somewhat important",
                 x == 3 ~ "Somewhat unimportant",
                 x == 4 ~ "Very unimportant",
                 x == 5 ~ "Completely unimportant")
  return(x)
}

approve <- function(x) {
  x <- case_when(x == 1 ~ "Strongly approve",
                 x == 2 ~ "Somewhat approve",
                 x == 3 ~ "Somewhat disapprove",
                 x == 4 ~ "Strongly disapprove",
                 x == 5 ~ "Not sure")
  return(x)
}

agree <- function(x) {
  x <- case_when(x == 1 ~ "Strongly disagree",
                 x == 2 ~ "Somewhat disagree",
                 x == 3 ~ "Neither agree nor disagree",
                 x == 4 ~ "Somewhat agree",
                 x == 5 ~ "Strongly agree")
  return(x)
}

agree_rev <- function(x) {
  x <- case_when(x == 1 ~ "Strongly agree",
                 x == 2 ~ "Somewhat agree",
                 x == 3 ~ "Neither agree nor disagree",
                 x == 4 ~ "Somewhat disagree",
                 x == 5 ~ "Strongly disagree")
  return(x)
}

knowledge <- function(x) {
  x <- case_when(x == 1 ~ "Republicans",
                 x == 2 ~ "Democrats",
                 x == 3 ~ "Neither",
                 x == 4 ~ "Not sure")
  return(x)
}

knowledge_race <- function(x) {
  x <- case_when(x == 1 ~ "White",
                 x == 2 ~ "Black",
                 x == 3 ~ "Hispanic",
                 x == 4 ~ "Asian",
                 x == 5 ~ "Other",
                 x == 6 ~ "Not sure")
  return(x)
}

namerec <- function(x) {
  x <- case_when(x == 1 ~ "Never heard of person",
                 x == 2 ~ "Republican",
                 x == 3 ~ "Democrat",
                 x == 4 ~ "Other party / independent",
                 x == 5 ~ "Not sure")
  return(x)
}

ideology_rating <- function(x) {
  x <- case_when(x == 1 ~ "Very liberal",
                 x == 2 ~ "Liberal",
                 x == 3 ~ "Somewhat liberal",
                 x == 4 ~ "Middle of the road",
                 x == 5 ~ "Somewhat conservative",
                 x == 6 ~ "Conservative",
                 x == 7 ~ "Very conservative",
                 x == 8 ~ "Not sure")
  return(x)
}

voted_post <- function(x) {
  x <- case_when(x == 1 ~ "Democratic candidate",
                 x == 2 ~ "Republican candidate",
                 x == 3 ~ "Other candidate",
                 x == 4 ~ "Did not vote in this race",
                 x == 5 ~ "There was no race for this office")
  return(x)
}

increase <- function(x) {
  x <- case_when(x == 1 ~ "Greatly increase",
                 x == 2 ~ "Slightly increase",
                 x == 3 ~ "Maintain",
                 x == 4 ~ "Slightly decrease",
                 x == 5 ~ "Greatly decrease")
  return(x)
}

grade <- function(x) {
  x <- case_when(x == 1 ~ "A - Excellent",
                 x == 2 ~ "B - Above average",
                 x == 3 ~ "C - Average",
                 x == 4 ~ "D - Below average",
                 x == 5 ~ "F - Poor")
  return(x)
}

# Actual processing #### 
cces_2016_full <- cces_2016_raw %>%
  left_join(state_fips %>% dplyr::select(state = State, FIPS), by = c("inputstate" = "FIPS")) %>%
  mutate(# Gender, sexuality, and family
         gender = case_when(gender == 1 ~ "Male",
                            gender == 2 ~ "Female"),
         sexuality = case_when(sexuality == 1 ~ "Heterosexual / straight",
                               sexuality == 2 ~ "Lesbian / gay woman",
                               sexuality == 3 ~ "Gay man",
                               sexuality == 4 ~ "Bisexual",
                               sexuality == 5 ~ "Other",
                               sexuality == 6 ~ "Prefer not to say"),
         trans = case_when(trans == 1 ~ "Yes",
                           trans == 2 ~ "No",
                           trans == 3 ~ "Prefer not to say"),
         marstat = case_when(marstat == 1 ~ "Married",
                             marstat == 2 ~ "Separated",
                             marstat == 3 ~ "Divorced",
                             marstat == 4 ~ "Widowed",
                             marstat == 5 ~ "Single",
                             marstat == 6 ~ "Domestic partnership"),
         child18 = binary12(child18),
         residence_length = case_when(CC16_361 == 1 ~ "Less than 1 month",
                                      CC16_361 == 2 ~ "2 to 6 months",
                                      CC16_361 == 3 ~ "7 to 11 months",
                                      CC16_361 == 4 ~ "1 to 2 years",
                                      CC16_361 == 5 ~ "3 to 4 years",
                                      CC16_361 == 6 ~ "5 or more years"),
         
         # Socioeconomic status
         educ = case_when(educ == 1 ~ "No HS",
                          educ == 2 ~ "High school graduate",
                          educ == 3 ~ "Some college",
                          educ == 4 ~ "2-year",
                          educ == 5 ~ "4-year",
                          educ == 6 ~ "Post-grad"),
         edloan = binary12(edloan),
         faminc = case_when(faminc == 1 ~ "Less than $10,000",
                            faminc == 2 ~ "$10,000 - $19,990",
                            faminc == 3 ~ "$20,000 - $29,999",
                            faminc == 4 ~ "$30,000 - $39,999",
                            faminc == 5 ~ "$40,000 - $49,999",
                            faminc == 6 ~ "$50,000 - $59,999",
                            faminc == 7 ~ "$60,000 - $69,999",
                            faminc == 8 ~ "$70,000 - $79,999",
                            faminc == 9 ~ "$80,000 - $99,999",
                            faminc == 10 ~ "$100,000 - $119,999",
                            faminc == 11 ~ "$120,000 - $149,999",
                            faminc == 12 ~ "$150,000 - $199,999",
                            faminc == 13 ~ "$200,000 - $249,999",
                            faminc == 14 ~ "$250,000 - $349,999",
                            faminc == 15 ~ "$350,000 - $499,999",
                            faminc == 16 ~ "$500,000 or more",
                            faminc == 31 ~ "$150,000 or more",
                            faminc == 32 ~ "$250,000 or more",
                            faminc == 97 ~ "Prefer not to say"),
         ownhome = case_when(ownhome == 1 ~ "Own",
                             ownhome == 2 ~ "Rent",
                             ownhome == 3 ~ "Other"),
         union = case_when(union == 1 ~ "Current union member",
                           union == 2 ~ "Former union member",
                           union == 3 ~ "Never a union member"),
         unionhh = case_when(unionhh == 1 ~ "Current union household",
                             unionhh == 2 ~ "Former union household",
                             unionhh == 3 ~ "Never a union household"),
         investor = binary12(investor),
         
         healthins_employer = binary12(healthins_1),
         healthins_gov = binary12(healthins_2),
         healthins_school = binary12(healthins_3),
         healthins_ind = binary12(healthins_4),
         healthins_unsure = binary12(healthins_5),
         no_healthins = binary12(healthins_6),
         
         # Race and ancestry
         race = case_when(race == 1 ~ "White",
                          race == 2 ~ "Black",
                          race == 3 ~ "Hispanic",
                          race == 4 ~ "Asian",
                          race == 5 ~ "Native American",
                          race == 8 ~ "Middle Eastern",
                          race == 6 ~ "Mixed",
                          race == 7 ~ "Other"),
         
         multrace_white = binary12(multrace_1),
         multrace_black = binary12(multrace_2),
         multrace_hispanic = binary12(multrace_3),
         multrace_asian = binary12(multrace_4),
         multrace_native = binary12(multrace_5),
         multrace_middle_east = binary12(multrace_8),
         multrace_other = binary12(multrace_97),
         multrace_dk = binary12(multrace_98),
         multrace_none = binary12(multrace_99),
         
         hispanic = binary12(hispanic),
         hispanic_none = binary12(Hispanic_origin_1),
         hispanic_usa = binary12(Hispanic_origin_2),
         hispanic_mex = binary12(Hispanic_origin_3),
         hispanic_pr = binary12(Hispanic_origin_4),
         hispanic_cub = binary12(Hispanic_origin_5),
         hispanic_dom = binary12(Hispanic_origin_6),
         hispanic_south_america = binary12(Hispanic_origin_7),
         hispanic_central_america = binary12(Hispanic_origin_8),
         hispanic_caribbean = binary12(Hispanic_origin_9),
         hispanic_esp = binary12(Hispanic_origin_10),
         hispanic_other = binary12(Hispanic_origin_11),
         not_hispanic = binary12(Hispanic_origin_12),

         asian_none = binary12(Asian_origin_1),
         asian_usa = binary12(Asian_origin_2),
         asian_chn = binary12(Asian_origin_3),
         asian_jpn = binary12(Asian_origin_4),
         asian_ind = binary12(Asian_origin_5),
         asian_phl = binary12(Asian_origin_6),
         asian_twn = binary12(Asian_origin_7),
         asian_kor = binary12(Asian_origin_8),
         asian_vnm = binary12(Asian_origin_9),
         asian_pak = binary12(Asian_origin_10),
         asian_hmong = binary12(Asian_origin_11),
         asian_khm = binary12(Asian_origin_12),
         asian_tha = binary12(Asian_origin_13),
         asian_other = binary12(Asian_origin_14),
         not_asian = binary12(Asian_origin_15),
         
         immstat = case_when(immstat == 1 ~ "Immigrant citizen",
                             immstat == 2 ~ "Immigrant non-citizen",
                             immstat == 3 ~ "First generation",
                             immstat == 4 ~ "Second generation",
                             immstat == 5 ~ "Third generation"),
         
         # Work and employment
         employ = case_when(employ == 1 ~ "Full-time",
                            employ == 2 ~ "Part-time",
                            employ == 3 ~ "Temporarily laid off",
                            employ == 4 ~ "Unemployed",
                            employ == 5 ~ "Retired",
                            employ == 6 ~ "Permanently disabled",
                            employ == 7 ~ "Homemaker",
                            employ == 8 ~ "Student",
                            employ == 9 ~ "Other"),
         hadjob = binary12(hadjob),
         
         # Military service
         milstat_resp_current = binary12(milstat_1),
         milstat_family_current = binary12(milstat_2),
         milstat_resp_previous = binary12(milstat_3),
         milstat_family_previous = binary12(milstat_4),
         milstat_never = binary12(milstat_5),
         
         # Media access and consumption
         phone = case_when(phone == 1 ~ "Both cell and landline",
                           phone == 2 ~ "Cell only",
                           phone == 3 ~ "Landline",
                           phone == 4 ~ "No phone"),
         internethome = case_when(internethome == 1 ~ "Broadband",
                                  internethome == 2 ~ "Dial-up",
                                  internethome == 3 ~ "No Internet at home"),
         internetwork = case_when(internetwork == 1 ~ "Broadband",
                                  internetwork == 2 ~ "Dial-up",
                                  internetwork == 3 ~ "No Internet at work"),
         newsint = case_when(newsint == 1 ~ "Most of the time",
                             newsint == 2 ~ "Some of the time",
                             newsint == 3 ~ "Only now and then",
                             newsint == 4 ~ "Hardly at all",
                             newsint == 7 ~ "Don't know"),
         pastday_blog = binary12(CC16_300_1),
         pastday_tv = binary12(CC16_300_2),
         pastday_newspaper = binary12(CC16_300_3),
         pastday_radio = binary12(CC16_300_4),
         pastday_social = binary12(CC16_300_5),
         pastday_no_media = binary12(CC16_300_6),
         
         news_region = case_when(CC16_300b == 1 ~ "Local newscast",
                                 CC16_300b == 2 ~ "National newscast",
                                 CC16_300b == 3 ~ "Both"),
         newspaper_medium = case_when(CC16_300c == 1 ~ "Print",
                                      CC16_300c == 2 ~ "Online",
                                      CC16_300c == 3 ~ "Both"),
         social_post = binary12(CC16_300d_1),
         social_comment = binary12(CC16_300d_2),
         social_read_watch = binary12(CC16_300d_3),
         social_follow_event = binary12(CC16_300d_4),
         social_forwarded = binary12(CC16_300d_5),
         
         # Campaign engagement
         pastyear_attendmeeting_post = binary12(CC16_417a_1),
         pastyear_politicalsign_post = binary12(CC16_417a_2),
         pastyear_workcampaign_post = binary12(CC16_417a_3),
         pastyear_politicaldonation_post = binary12(CC16_417a_4),
         pastyear_blooddonation_post = binary12(CC16_417a_5),
         pastyear_none = binary12(CC16_417a_6),
         
         donated_pres_post = binary12(CC16_417bx_1),
         donated_senate_homestate_post = binary12(CC16_417bx_2),
         donated_senate_otherstate_post = binary12(CC16_417bx_3),
         donated_house_homestate_post = binary12(CC16_417bx_4),
         donated_house_otherstate_post = binary12(CC16_417bx_5),
         donated_state_candidate_post = binary12(CC16_417bx_6),
         donated_party_post = binary12(CC16_417bx_7),
         donated_workpac_post = binary12(CC16_417bx_8),
         donated_nonworkpac_post = binary12(CC16_417bx_9),
         donated_other_post = binary12(CC16_417bx_10),
         
         contrib_influencepolicy_post = agree(CC16_417e_1),
         contrib_helpbusiness_post = agree(CC16_417e_2),
         contrib_network_post = agree(CC16_417e_3),
         contrib_candidatesonly_post = agree(CC16_417e_4),
         contrib_civicduty_post = agree(CC16_417e_5),
         
         contacted_by_org_post = binary12(CC16_425a),
         contact_inperson_post = binary12(CC416_25b_1),
         contact_phone_post = binary12(CC416_25b_2),
         contact_emailtext_post = binary12(CC416_25b_3),
         contact_mail = binary12(CC416_25b_4),
         
         ever_run_post = binary12(CC16_418a),
         ever_run_schoolboard_post = binary12(CC16_418bx_1),
         ever_run_localboard_post = binary12(CC16_418bx_2),
         ever_run_citycouncil_post = binary12(CC16_418bx_3),
         ever_run_mayor_post = binary12(CC16_418bx_4),
         ever_run_da_post = binary12(CC16_418bx_5),
         ever_run_county_post = binary12(CC16_418bx_6),
         ever_run_stateleg_post = binary12(CC16_418bx_7),
         ever_run_state_post = binary12(CC16_418bx_8),
         ever_run_federal_post = binary12(CC16_418bx_9),
         ever_run_judge_post = binary12(CC16_418bx_10),
         ever_run_other_post = binary12(CC16_418bx_11),
         
         # Political identification and ideology
         pid7 = case_when(pid7 == 1 ~ "Strong Democrat",
                          pid7 == 2 ~ "Not very strong Democrat",
                          pid7 == 7 ~ "Strong Republican",
                          pid7 == 6 ~ "Not very strong Republican",
                          pid7 == 3 ~ "Lean Democrat",
                          pid7 == 5 ~ "Lean Republican",
                          pid7 == 4 ~ "Independent",
                          pid7 == 8 ~ "Not sure"),
         pid3 = case_when(pid3 == 1 ~ "Democrat",
                          pid3 == 2 ~ "Republican",
                          pid3 == 3 ~ "Independent",
                          pid3 == 4 ~ "Other",
                          pid3 == 5 ~ "Not sure"),
         pid3_post = case_when(CC16_421a == 1 ~ "Democrat",
                               CC16_421a == 2 ~ "Republican",
                               CC16_421a == 3 ~ "Independent",
                               CC16_421a == 4 ~ "Other"),
         demstrength_post = case_when(CC16_421_dem == 1 ~ "Strong Democrat",
                                      CC16_421_dem == 2 ~ "Not so strong Democrat"),
         repstrength_post = case_when(CC16_421_rep == 1 ~ "Strong Republican",
                                      CC16_421_rep == 2 ~ "Not so strong Republican"),
         indlean_post = case_when(CC16_421b == 1 ~ "Lean Democrat",
                                  CC16_421b == 2 ~ "Lean Republican",
                                  CC16_421b == 3 ~ "Neither",
                                  CC16_421b == 8 ~ "Not sure"),
         ideo5 = case_when(ideo5 == 1 ~ "Very liberal",
                           ideo5 == 2 ~ "Liberal",
                           ideo5 == 3 ~ "Moderate",
                           ideo5 == 4 ~ "Conservative",
                           ideo5 == 5 ~ "Very conservative",
                           ideo5 == 6 ~ "Not sure"),
         partyreg = case_when(CC16_360 == 1 ~ "No party / independent / decline to state",
                              CC16_360 == 2 ~ "Democratic Party",
                              CC16_360 == 3 ~ "Republican Party",
                              CC16_360 == 4 ~ "Other"),
         
         # Political behavior and attitudes
         impt_guns = importance(CC16_301a),
         impt_abortion = importance(CC16_301b),
         impt_tax = importance(CC16_301c),
         impt_imm = importance(CC16_301d),
         impt_deficit = importance(CC16_301e),
         impt_defense_spending = importance(CC16_301f),
         impt_social_security = importance(CC16_301g),
         impt_env = importance(CC16_301h),
         impt_jobs = importance(CC16_301i),
         impt_crime = importance(CC16_301j),
         impt_security = importance(CC16_301k),
         impt_race = importance(CC16_301l),
         impt_healthcare = importance(CC16_301m),
         impt_gay_marriage = importance(CC16_301n),
         impt_corruption = importance(CC16_301o),
         
         pastyear_change_national_economy = case_when(CC16_302 == 1 ~ "Gotten much better",
                                                      CC16_302 == 2 ~ "Gotten better",
                                                      CC16_302 == 3 ~ "Stayed about the same",
                                                      CC16_302 == 4 ~ "Gotten worse",
                                                      CC16_302 == 5 ~ "Gotten much worse",
                                                      CC16_302 == 6 ~ "Not sure"),
         pastyear_change_household_income = case_when(CC16_303 == 1 ~ "Increased a lot",
                                                      CC16_303 == 2 ~ "Increased somewhat",
                                                      CC16_303 == 3 ~ "Stayed about the same",
                                                      CC16_303 == 4 ~ "Decreased somewhat",
                                                      CC16_303 == 5 ~ "Decreased a lot"),
         nextyear_change_national_economy = case_when(CC16_304 == 1 ~ "Get much betteR",
                                                      CC16_304 == 2 ~ "Get somewhat better",
                                                      CC16_304 == 3 ~ "Stay about the same",
                                                      CC16_304 == 4 ~ "Get somewhat worse",
                                                      CC16_304 == 5 ~ "Get much worse",
                                                      CC16_304 == 6 ~ "Not sure"),
         
         police_safe = case_when(CC16_307 == 1 ~ "Mostly safe",
                                 CC16_307 == 2 ~ "Somewhat safe",
                                 CC16_307 == 3 ~ "Somewhat unsafe",
                                 CC16_307 == 4 ~ "Mostly unsafe"),
         
         isis_stayout = binary12(CC16_312_1),
         isis_sendhumaid = binary12(CC16_312_2),
         isis_sendmilaid = binary12(CC16_312_3),
         isis_nofly = binary12(CC16_312_4),
         isis_airstrikes = binary12(CC16_312_5),
         isis_sendadvisors = binary12(CC16_312_6),
         isis_sendtroops = binary12(CC16_312_7),
         
         guns_backgroundchecks = binary12(CC16_330a),
         guns_prohibitregistry = binary12(CC16_330b),
         guns_assaultban = binary12(CC16_330d),
         guns_concealed = binary12(CC16_330e),
         
         imm_amnesty = binary12(CC16_331_1),
         imm_moresecurity = binary12(CC16_331_2),
         imm_dream = binary12(CC16_331_3),
         imm_finebusinesses = binary12(CC16_331_4),
         imm_bansyrianrefugees = binary12(CC16_331_5),
         imm_moreworkvisas = binary12(CC16_331_6),
         imm_deport = binary12(CC16_331_7),
         imm_muslimban = binary12(CC16_331_8),
         imm_none = binary12(CC16_331_9),
         
         abortion_always = binary12(CC16_332a),
         abortion_rapeincesthealth = binary12(CC16_332b),
         abortion_20wkban = binary12(CC16_332c),
         abortion_noinsurance = binary12(CC16_332d),
         abortion_hyde = binary12(CC16_332e),
         abortion_never = binary12(CC16_332f),
         
         env_co2reg = binary12(CC16_333a),
         env_35mpg = binary12(CC16_333b),
         env_renewablereq = binary12(CC16_333c),
         env_cleanacts = binary12(CC16_333d),
         
         crime_nomindrugsentences = binary12(CC16_334a),
         crime_bodycameras = binary12(CC16_334b),
         crime_morepolice = binary12(CC16_334c),
         crime_longersentences = binary12(CC16_334d),
         
         mil_secureoil_post = binary12(CC16_414_1),
         mil_destroycamp_post = binary12(CC16_414_2),
         mil_genocidecivilwar_post = binary12(CC16_414_3),
         mil_spreaddemocracy_post = binary12(CC16_414_4),
         mil_protectallies_post = binary12(CC16_414_5),
         mil_helpun_post = binary12(CC16_414_6),
         mil_none_post = binary12(CC16_414_7),
         
         gay_marriage = binary12(CC16_335),
         
         approve_obama = approve(CC16_320a),
         approve_congress = approve(CC16_320b),
         approve_scotus = approve(CC16_320c),
         approve_governor = approve(CC16_320d),
         approve_legislature = approve(CC16_320e),
         approve_rep = approve(CC16_320f),
         approve_senator_1 = approve(CC16_320g),
         approve_senator_2 = approve(CC16_320h),
         
         support_garland = binary12(CC16_351A),
         support_tpp = binary12(CC16_351B),
         support_freedomact = binary12(CC16_351C),
         support_taa = binary12(CC16_351D),
         support_nclbrepeal = binary12(CC16_351E),
         support_infrastructure = binary12(CC16_351F),
         support_iransanctions = binary12(CC16_351G),
         support_capitatedmedicare = binary12(CC16_351H),
         support_acarepeal = binary12(CC16_351I),
         support_12minwage = binary12(CC16_351K),
         
         racism_angry_post = agree_rev(CC16_422c),
         racism_whiteprivilege_post = agree_rev(CC16_422d),
         racism_fear_post = agree_rev(CC16_422e),
         racism_isolatedincidents_post = agree_rev(CC16_422f),
         
         state_spending_welfare_post = increase(CC16_426_1), 
         state_spending_healthcare_post = increase(CC16_426_2),
         state_spending_education_post = increase(CC16_426_3),
         state_spending_law_post = increase(CC16_426_4),
         state_spending_infrastructure_post = increase(CC16_426_5),
         
         # Voting
         votereg = case_when(votereg == 1 ~ "Yes",
                             votereg == 2 ~ "No",
                             votereg == 3 ~ "Don't know"),
         pres_vote_2012 = case_when(CC16_326 == 1 ~ "Barack Obama",
                                    CC16_326 == 2 ~ "Mitt Romney",
                                    CC16_326 == 3 ~ "Someone else",
                                    CC16_326 == 4 ~ "Did not vote",
                                    CC16_326 == 5 ~ "Don't recall"),
         voted_2016_primary = binary12(CC16_327),
         primary_vote_2016 = case_when(CC16_328 == 1 ~ "Hillary Clinton",
                                       CC16_328 == 2 ~ "Bernie Sanders",
                                       CC16_328 == 3 ~ "Another Democrat",
                                       CC16_328 == 4 ~ "Donald Trump",
                                       CC16_328 == 5 ~ "Ted Cruz",
                                       CC16_328 == 6 ~ "John Kasich",
                                       CC16_328 == 7 ~ "Marco Rubio",
                                       CC16_328 == 8 ~ "Another Republican",
                                       CC16_328 == 9 ~ "Someone else who is not a Democrat or Republican"),
         plan_to_vote = case_when(CC16_364 == 1 ~ "Yes, definitely",
                                  CC16_364 == 2 ~ "Probably",
                                  CC16_364 == 3 ~ "I already voted (early or absentee)",
                                  CC16_364 == 4 ~ "No",
                                  CC16_364 == 5 ~ "Undecided"),
         early_pres_vote = case_when(CC16_364b == 1 ~ "Donald Trump (R)",
                                     CC16_364b == 2 ~ "Hillary Clinton (D)",
                                     CC16_364b == 3 ~ "Gary Johnson (L)",
                                     CC16_364b == 4 ~ "Jill Stein (G)",
                                     CC16_364b == 5 ~ "Other",
                                     CC16_364b == 6 ~ "I didn't vote in this election",
                                     CC16_364b == 7 ~ "Not sure"),
         pres_preference = case_when(CC16_364c == 1 ~ "Donald Trump (R)",
                                     CC16_364c == 2 ~ "Hillary Clinton (D)",
                                     CC16_364c == 3 ~ "Gary Johnson (L)",
                                     CC16_364c == 4 ~ "Jill Stein (G)",
                                     CC16_364c == 5 ~ "Other",
                                     CC16_364c == 6 ~ "I won't vote in this election",
                                     CC16_364c == 7 ~ "Not sure"),
         senate_preference = case_when(CC16_365 == 1 ~ SenCand1Party,
                                       CC16_365 == 2 ~ SenCand2Party,
                                       CC16_365 == 3 ~ SenCand3Party,
                                       CC16_365 == 4 ~ SenCand4Party),
         governor_preference = case_when(CC16_365 == 1 ~ GovCand1Party,
                                         CC16_365 == 2 ~ GovCand2Party,
                                         CC16_365 == 3 ~ GovCand3Party),
         house_preference = case_when(CC16_367 == 1 ~ HouseCand1Party,
                                      CC16_367 == 2 ~ HouseCand2Party,
                                      CC16_367 == 3 ~ HouseCand3Party,
                                      CC16_367 == 4 ~ HouseCand4Party),
         votereg_post = binary12(votereg_post),
         voted_2016_post = case_when(CC16_401 == 1 ~ "I did not vote in the election this November",
                                     CC16_401 == 2 ~ "I thought about voting this time but didn't",
                                     CC16_401 == 3 ~ "I usually vote, but didn't this time",
                                     CC16_401 == 4 ~ "I attempted to vote but did not or could not",
                                     CC16_401 == 5 ~ "I definitely voted in the general election"),
         reason_didnt_vote_post = case_when(CC16_402a == 1 ~ "I forgot",
                                            CC16_402a == 2 ~ "I'm not interested",
                                            CC16_402a == 3 ~ "Too busy",
                                            CC16_402a == 4 ~ "Did not like the candidates",
                                            CC16_402a == 5 ~ "I am not registered",
                                            CC16_402a == 6 ~ "I did not have the correct form of identification",
                                            CC16_402a == 7 ~ "Out of town",
                                            CC16_402a == 8 ~ "Sick or disabled",
                                            CC16_402a == 9 ~ "Transportation",
                                            CC16_402a == 10 ~ "Bad weather",
                                            CC16_402a == 11 ~ "The line at the polls was too long",
                                            CC16_402a == 12 ~ "I was not allowed to vote at the polls, even though I tried",
                                            CC16_402a == 13 ~ "I requested but did not receive an absentee ballot",
                                            CC16_402a == 14 ~ "I did not know where to vote",
                                            CC16_402a == 15 ~ "I did not feel that I knew enough about the choices",
                                            CC16_402a == 16 ~ "Other",
                                            CC16_402a == 55 ~ "Don't know"),
         reason_didnt_vote_second_post = case_when(CC16_402a == 1 ~ "I forgot",
                                                   CC16_402a == 2 ~ "I'm not interested",
                                                   CC16_402a == 3 ~ "Too busy",
                                                   CC16_402a == 4 ~ "Did not like the candidates",
                                                   CC16_402a == 5 ~ "I am not registered",
                                                   CC16_402a == 6 ~ "I did not have the correct form of identification",
                                                   CC16_402a == 7 ~ "Out of town",
                                                   CC16_402a == 8 ~ "Sick or disabled",
                                                   CC16_402a == 9 ~ "Transportation",
                                                   CC16_402a == 10 ~ "Bad weather",
                                                   CC16_402a == 11 ~ "The line at the polls was too long",
                                                   CC16_402a == 12 ~ "I was not allowed to vote at the polls, even though I tried",
                                                   CC16_402a == 13 ~ "I requested but did not receive an absentee ballot",
                                                   CC16_402a == 14 ~ "I did not know where to vote",
                                                   CC16_402a == 15 ~ "I did not feel that I knew enough about the choices",
                                                   CC16_402a == 16 ~ "Other",
                                                   CC16_402a == 55 ~ "Don't know"),
         vote_method_post = case_when(CC16_403 == 1 ~ "In person on election day",
                                      CC16_403 == 2 ~ "In person before election day (early)",
                                      CC16_403 == 3 ~ "Voted by mail (or absentee)",
                                      CC16_403 == 4 ~ "Don't know"),
         vote_location_post = case_when(CC16_403b == 1 ~ "At a precinct polling place",
                                        CC16_403b == 2 ~ "At a vote center"),
         vote_wait_time_post = case_when(CC16_404 == 1 ~ "Not at all",
                                         CC16_404 == 2 ~ "Less than 10 minutes",
                                         CC16_404 == 3 ~ "10 - 30 minutes",
                                         CC16_404 == 4 ~ "31 minutes - 1 hour",
                                         CC16_404 == 5 ~ "More than 1 hour",
                                         CC16_404 == 6 ~ "Don't know"),
         same_day_reg_post = binary12(CC16_405),
         
         voter_reg_problem_post = case_when(CC16_406a == 1 ~ "No",
                                            CC16_406a == 2 ~ "Yes"),
         vote_problem_id_post = binary12(CC16_406b_1),
         vote_problem_reg_post = binary12(CC16_406b_2),
         vote_problem_place_post = binary12(CC16_406b_3),
         vote_problem_other_post = binary12(CC16_406b_4),
         
         vote_allowed_post = case_when(CC16_406c == 1 ~ "No, I was not allowed to vote",
                                       CC16_406c == 2 ~ "I was allowed to vote using a provisional ballot",
                                       CC16_406c == 3 ~ "I voted"),
         
         vote_intimidated_post = case_when(CC16_407a == 1 ~ "Yes",
                                           CC16_407a == 2 ~ "No",
                                           CC16_407a == 3 ~ "Don't remember"),
         pres_vote_2016_post = case_when(CC16_410a == 1 ~ "Donald Trump (R)",
                                         CC16_410a == 2 ~ "Hillary Clinton (D)",
                                         CC16_410a == 3 ~ "Gary Johnson (L)",
                                         CC16_410a == 4 ~ "Jill Stein (G)",
                                         CC16_410a == 8 ~ "Evan McMullin (I)",
                                         CC16_410a == 5 ~ "Other",
                                         CC16_410a == 6 ~ "I didn't vote in this election",
                                         CC16_410a == 7 ~ "I'm not sure"),
         pres_nonvoter_pref_2016_post = case_when(CC16_410a_nv == 1 ~ "Donald Trump (R)",
                                                  CC16_410a_nv == 2 ~ "Hillary Clinton (D)",
                                                  CC16_410a_nv == 3 ~ "Gary Johnson (L)",
                                                  CC16_410a_nv == 4 ~ "Jill Stein (G)",
                                                  CC16_410a_nv == 8 ~ "Evan McMullin (I)",
                                                  CC16_410a_nv == 5 ~ "Other",
                                                  CC16_410a_nv == 6 ~ "I didn't vote in this election",
                                                  CC16_410a_nv == 7 ~ "I'm not sure"),
         senate_vote_2016_post = case_when(CC16_410b == 1 ~ SenCand1Party_post,
                                           CC16_410b == 2 ~ SenCand2Party_post,
                                           CC16_410b == 3 ~ SenCand3Party_post,
                                           CC16_410b == 4 ~ SenCand4Party_post),
         governor_vote_2016_post = case_when(CC16_411 == 1 ~ GovCand1Party_post,
                                             CC16_411 == 2 ~ GovCand2Party_post,
                                             CC16_411 == 3 ~ GovCand3Party_post),
         house_vote_2016_post = case_when(CC16_412 == 1 ~ HouseCand1Party_post,
                                          CC16_412 == 2 ~ HouseCand2Party_post,
                                          CC16_412 == 3 ~ HouseCand3Party_post,
                                          CC16_412 == 4 ~ HouseCand4Party_post),
         
         ag_vote_2016_post = voted_post(CC16_413a),
         sos_vote_2016_post = voted_post(CC16_413b),
         state_senate_vote_2016_post = voted_post(CC16_413c),
         state_house_vote_2016_post = voted_post(CC16_413d),
         
         # Political knowledge and perceptions
         know_house_maj = knowledge(CC16_321a),
         know_sen_maj = knowledge(CC16_321b),
         know_state_sen_maj = knowledge(CC16_321c),
         know_state_house_maj = knowledge(CC16_321d),
         know_scotus_maj = case_when(CC16_350 == 1 ~ "Most were appointed by Democratic presidents",
                                     CC16_350 == 2 ~ "Most were appointed by Republican presidents",
                                     CC16_350 == 3 ~ "An equal number were appointed by Democratic and Republican presidents",
                                     CC16_350 == 4 ~ "Not sure"),
         
         know_housecand1_race_post = knowledge_race(CC16_423a),
         know_housecand2_race_post = knowledge_race(CC16_423b),
         know_rep_race_post = knowledge_race(CC16_423c),
         
         rec_governor = namerec(CC16_322a),
         rec_senator_1 = namerec(CC16_322b),
         rec_senator_2 = namerec(CC16_322c),
         rec_rep = namerec(CC16_322d),
         
         ideology_self = ideology_rating(CC16_340a),
         ideology_governor = ideology_rating(CC16_340b),
         ideology_obama = ideology_rating(CC16_340c),
         ideology_clinton = ideology_rating(CC16_340d),
         ideology_trump = ideology_rating(CC16_340e),
         ideology_garland = ideology_rating(CC16_340f),
         ideology_democrats = ideology_rating(CC16_340g),
         ideology_republicans = ideology_rating(CC16_340h),
         ideology_scotus = ideology_rating(CC16_340i),
         ideology_senator_1 = ideology_rating(CC16_340j),
         ideology_senator_2 = ideology_rating(CC16_340k),
         ideology_senate_cand1 = ideology_rating(CC16_340l),
         ideology_senate_cand2 = ideology_rating(CC16_340m),
         ideology_house_cand1 = ideology_rating(CC16_340n),
         ideology_house_cand2 = ideology_rating(CC16_340o),
         ideology_rep = ideology_rating(CC16_340p),
         
         community_grade_schools_post = grade(CC16_427_a),
         community_grade_police_post = grade(CC16_427_b),
         community_grade_road_post = grade(CC16_427_c),
         community_grade_zoning_post = grade(CC16_427_d),
         community_grade_mayor_post = grade(CC16_427_e),
         community_grade_council_post = grade(CC16_427_f),
         
         # The past four years
         past4year_married = binary12(CC16_305_1),
         past4year_lostjob = binary12(CC16_305_2),
         past4year_graduated = binary12(CC16_305_3),
         past4year_retired = binary12(CC16_305_4),
         past4year_divorced = binary12(CC16_305_5),
         past4year_hadchild = binary12(CC16_305_6),
         past4year_newjob = binary12(CC16_305_7),
         past4year_ticket = binary12(CC16_305_8),
         past4year_crimevictim = binary12(CC16_305_9),
         past4year_er = binary12(CC16_305_10),
         past4year_raise = binary12(CC16_305_11),
         
         # Religion
         pew_bornagain = binary12(pew_bornagain),
         pew_religimp = case_when(pew_religimp == 1 ~ "Very important",
                                  pew_religimp == 2 ~ "Somewhat important",
                                  pew_religimp == 3 ~ "Not too important",
                                  pew_religimp == 4 ~ "Not at all important"),
         pew_churatd = case_when(pew_churatd == 1 ~ "More than once a week",
                                 pew_churatd == 2 ~ "Once a week",
                                 pew_churatd == 3 ~ "Once or twice a month",
                                 pew_churatd == 4 ~ "A few times a year",
                                 pew_churatd == 5 ~ "Seldom",
                                 pew_churatd == 6 ~ "Never",
                                 pew_churatd == 7 ~ "Don't know"),
         pew_prayer = case_when(pew_prayer == 1 ~ "Several times a day",
                                pew_prayer == 2 ~ "Once a day",
                                pew_prayer == 3 ~ "A few times a week",
                                pew_prayer == 4 ~ "Once a week",
                                pew_prayer == 5 ~ "A few times a month",
                                pew_prayer == 6 ~ "Seldom",
                                pew_prayer == 7 ~ "Never",
                                pew_prayer == 8 ~ "Don't know"),
         religpew = case_when(religpew == 1 ~ "Protestant",
                              religpew == 2 ~ "Roman Catholic",
                              religpew == 3 ~ "Mormon",
                              religpew == 4 ~ "Eastern or Greek Orthodox",
                              religpew == 5 ~ "Jewish",
                              religpew == 6 ~ "Muslim",
                              religpew == 7 ~ "Buddhist",
                              religpew == 8 ~ "Hindu",
                              religpew == 9 ~ "Atheist",
                              religpew == 10 ~ "Agnostic",
                              religpew == 11 ~ "Nothing in particular",
                              religpew == 12 ~ "Something else"),
         religpew_protestant = case_when(religpew_protestant == 1 ~ "Baptist",
                                         religpew_protestant == 2 ~ "Methodist",
                                         religpew_protestant == 3 ~ "Nondenominational or Independent Church",
                                         religpew_protestant == 4 ~ "Lutheran",
                                         religpew_protestant == 5 ~ "Presbyterian",
                                         religpew_protestant == 6 ~ "Pentecostal",
                                         religpew_protestant == 7 ~ "Episcopalian",
                                         religpew_protestant == 8 ~ "Church of Christ or Disciples of Christ",
                                         religpew_protestant == 9 ~ "Congregational or United Church of Christ",
                                         religpew_protestant == 10 ~ "Holiness",
                                         religpew_protestant == 11 ~ "Reformed",
                                         religpew_protestant == 12 ~ "Adventist",
                                         religpew_protestant == 13 ~ "Jehovah's Witness",
                                         religpew_protestant == 90 ~ "Something else"),
         religpew_baptist = case_when(religpew_baptist == 1 ~ "Southern Baptist Convention",
                                      religpew_baptist == 2 ~ "American Baptist Churches in USA",
                                      religpew_baptist == 3 ~ "National Baptist Convention",
                                      religpew_baptist == 4 ~ "Progressive Baptist Convention",
                                      religpew_baptist == 5 ~ "Independent Baptist",
                                      religpew_baptist == 6 ~ "Baptist General Conference",
                                      religpew_baptist == 7 ~ "Baptist Missionary ASsociation",
                                      religpew_baptist == 8 ~ "Conservative Baptist Association of America",
                                      religpew_baptist == 9 ~ "Free Will Baptist",
                                      religpew_baptist == 10 ~ "General Association of Regular Baptists",
                                      religpew_baptist == 11 ~ "Other Baptist"),
         religpew_methodist = case_when(religpew_methodist == 1 ~ "United Methodist Church",
                                        religpew_methodist == 2 ~ "Free Methodist Church",
                                        religpew_methodist == 3 ~ "African Methodist Episcopal",
                                        religpew_methodist == 4 ~ "African Methodist Episcopal Zion",
                                        religpew_methodist == 5 ~ "Christian Methodist Episcopal Church",
                                        religpew_methodist == 90 ~ "Other Methodist Church"),
         religpew_nondenom = case_when(religpew_nondenom == 1 ~ "Nondenominational evangelical",
                                       religpew_nondenom == 2 ~ "Nondemoninational fundamentalist",
                                       religpew_nondenom == 3 ~ "Nondenominational charismatic",
                                       religpew_nondenom == 4 ~ "Interdenominational",
                                       religpew_nondenom == 5 ~ "Community church",
                                       religpew_nondenom == 90 ~ "Other"),
         religpew_lutheran = case_when(religpew_lutheran == 1 ~ "Evangelical Lutheran Church in America (ELCA)",
                                       religpew_lutheran == 2 ~ "Lutheran Church, Missouri Synod",
                                       religpew_lutheran == 3 ~ "Lutheran Church, Wisconsin Synod",
                                       religpew_lutheran == 4 ~ "Other Lutheran Church"),
         religpew_presby = case_when(religpew_presby == 1 ~ "Presbyterian Church USA",
                                     religpew_presby == 2 ~ "Presbyterian Church in America",
                                     religpew_presby == 3 ~ "Associate Reforemd Presbyterian",
                                     religpew_presby == 4 ~ "Cumberland Presbyterian Church",
                                     religpew_presby == 5 ~ "Orthodox Presbyterian",
                                     religpew_presby == 6 ~ "Evangelical Presbyterian Church",
                                     religpew_presby == 90 ~ "Other Presbyterian Church"),
         religpew_pentecost = case_when(religpew_pentecost == 1 ~ "Assemblies of God",
                                        religpew_pentecost == 2 ~ "Church of God Cleveland TN",
                                        religpew_pentecost == 3 ~ "Four Square Gospel",
                                        religpew_pentecost == 4 ~ "Pentecostal Church of God",
                                        religpew_pentecost == 5 ~ "Pentecostal Holiness Church",
                                        religpew_pentecost == 6 ~ "Church of God in Christ",
                                        religpew_pentecost == 7 ~ "Church of God of the Apostolic Faith",
                                        religpew_pentecost == 8 ~ "Assembly of Christian Churches",
                                        religpew_pentecost == 9 ~ "Apostolic Christian",
                                        religpew_pentecost == 90 ~ "Other Pentecostal Church"),
         religpew_episcop = case_when(religpew_episcop == 1 ~ "Episcopal Church in the USA",
                                      religpew_episcop == 2 ~ "Anglican Church (Church of England)",
                                      religpew_episcop == 3 ~ "Anglican Orthodox Church",
                                      religpew_episcop == 4 ~ "Reformed Episcopal Church",
                                      religpew_episcop == 90 ~ "Other Episcopalian or Anglican Church"),
         religpew_congreg = case_when(religpew_congreg == 1 ~ "United Church of Christ",
                                      religpew_congreg == 2 ~ "Conservative Congregational Christian",
                                      religpew_congreg == 3 ~ "National Association of Congregational Christians",
                                      religpew_congreg == 4 ~ "Other Congregational"),
         religpew_holiness = case_when(religpew_holiness == 1 ~ "Church of the Nazarene",
                                       religpew_holiness == 2 ~ "Wesleyan Church",
                                       religpew_holiness == 3 ~ "Free Methodist Church",
                                       religpew_holiness == 4 ~ "Christian and Missionary Alliance",
                                       religpew_holiness == 5 ~ "Church of God (Anderson, Indiana)",
                                       religpew_holiness == 6 ~ "Salvation Army, American Rescue workers",
                                       religpew_holiness == 90 ~ "Other Holiness"),
         religpew_reformed = case_when(religpew_reformed == 1 ~ "Reformed Church in America",
                                       religpew_reformed == 2 ~ "Christian Reformed Church",
                                       religpew_reformed == 90 ~ "Other Reformed"),
         religpew_catholic = case_when(religpew_catholic == 1 ~ "Roman Catholic Church",
                                       religpew_catholic == 2 ~ "National Polish Catholic Church",
                                       religpew_catholic == 3 ~ "Greek-rite Catholic",
                                       religpew_catholic == 4 ~ "Armenian Catholic",
                                       religpew_catholic == 5 ~ "Old Catholic",
                                       religpew_catholic == 90 ~ "Other Catholic"),
         religpew_mormon = case_when(religpew_mormon == 1 ~ "The Church of Jesus Christ of Latter-day Saints",
                                     religpew_mormon == 2 ~ "Community of Christ",
                                     religpew_mormon == 90 ~ "Other Mormon"),
         religpew_orthodox = case_when(religpew_orthodox == 1 ~ "Greek Orthodox",
                                       religpew_orthodox == 2 ~ "Russian Orthodox",
                                       religpew_orthodox == 3 ~ "Orthodox Church in America",
                                       religpew_orthodox == 4 ~ "Armenian Orthodox",
                                       religpew_orthodox == 5 ~ "Eastern Orthodox",
                                       religpew_orthodox == 6 ~ "Serbian Orthodox",
                                       religpew_orthodox == 90 ~ "Other Orthodox"),
         religpew_jewish = case_when(religpew_jewish == 1 ~ "Reform",
                                     religpew_jewish == 2 ~ "Conservative",
                                     religpew_jewish == 3 ~ "Orthodox",
                                     religpew_jewish == 4 ~ "Reconstructionist",
                                     religpew_jewish == 90 ~ "Other"),
         religpew_muslim = case_when(religpew_muslim == 1 ~ "Sunni",
                                     religpew_muslim == 2 ~ "Shia",
                                     religpew_muslim == 3 ~ "Nation of Islam (Black Muslim)",
                                     religpew_muslim == 90 ~ "Other Muslim"),
         religpew_buddhist = case_when(religpew_buddhist == 1 ~ "Theravada (Vipassana) Buddhism",
                                       religpew_buddhist == 2 ~ "Mahayana (Zen) Buddhism",
                                       religpew_buddhist == 3 ~ "Vajrayana (Tibetan) Buddhism",
                                       religpew_buddhist == 90 ~ "Other Buddhist"),
         religpew_hindu = case_when(religpew_hindu == 1 ~ "Vaishnava Hinduism",
                                    religpew_hindu == 2 ~ "Shaivite Hinduism",
                                    religpew_hindu == 3 ~ "Shaktism Hinduism",
                                    religpew_hindu == 90 ~ "Other Hindu")
         ) %>%
  dplyr::select(id = V101, commonweight, commonweight_post, commonweight_vv, commonweight_vv_post, commonweight_vv_lgbt, tookpost,
                zip = lookupzip, state, cdid113, cdid115, countyfips, countyname, cdid113_post, cdid115_post, countyfips_post, countyname_post,
                birthyr, gender, sexuality, trans, educ, edloan, votereg, regzip, race, race_other, multrace_white, multrace_black,
                multrace_hispanic, multrace_asian, multrace_native, multrace_middle_east, multrace_other, multrace_dk, multrace_none,
                hispanic, hispanic_none, hispanic_usa, hispanic_mex, hispanic_pr, hispanic_cub, hispanic_dom, hispanic_south_america,
                hispanic_central_america, hispanic_caribbean, hispanic_esp, hispanic_other, not_hispanic, asian_none, asian_usa, asian_chn,
                asian_jpn, asian_ind, asian_phl, asian_twn, asian_kor, asian_vnm, asian_pak, asian_hmong, asian_khm, asian_tha, asian_other,
                not_asian, employ, hadjob, whatkindofwork, jobactivities, industryclass, phone, internethome, internetwork, marstat, pid7,
                pid3, ideo5, pew_bornagain, pew_religimp, pew_churatd, pew_prayer, religpew, religpew_protestant, religpew_baptist,
                religpew_methodist, religpew_nondenom, religpew_presby, religpew_pentecost, religpew_episcop, religpew_christian,
                religpew_congreg, religpew_holiness, religpew_reformed, religpew_advent, religpew_catholic, religpew_mormon, religpew_orthodox,
                religpew_jewish, religpew_muslim, religpew_buddhist, religpew_hindu, child18, child18num, newsint, faminc, ownhome, 
                residence_length, milstat_resp_current, milstat_family_current, milstat_resp_previous, milstat_family_previous, milstat_never,
                immstat, union, unionhh, investor, healthins_employer, healthins_gov, healthins_school, healthins_ind, healthins_unsure,
                no_healthins, pastday_blog, pastday_tv, pastday_newspaper, pastday_radio, pastday_social, pastday_no_media, news_region,
                newspaper_medium, social_post, social_comment, social_read_watch, social_follow_event, social_forwarded, impt_guns,
                impt_abortion, impt_tax, impt_imm, impt_deficit, impt_defense_spending, impt_social_security, impt_env, impt_jobs, impt_crime,
                impt_security, impt_race, impt_healthcare, impt_gay_marriage, impt_corruption, pastyear_change_national_economy,
                pastyear_change_household_income, nextyear_change_national_economy, past4year_married, past4year_lostjob, past4year_graduated,
                past4year_retired, past4year_divorced, past4year_hadchild, past4year_newjob, past4year_ticket, past4year_crimevictim,
                past4year_er, past4year_raise, police_safe, isis_stayout, isis_sendhumaid, isis_sendmilaid, isis_nofly, isis_airstrikes,
                isis_sendadvisors, isis_sendtroops, approve_obama, approve_congress, approve_scotus, approve_governor, approve_legislature,
                approve_rep, approve_senator_1, approve_senator_2, know_house_maj, know_sen_maj, know_state_sen_maj, know_state_house_maj,
                know_scotus_maj, rec_governor, rec_senator_1, rec_senator_2, rec_rep, pres_vote_2012, voted_2016_primary, primary_vote_2016,
                guns_backgroundchecks, guns_prohibitregistry, guns_assaultban, guns_concealed, imm_amnesty, imm_moresecurity, imm_dream,
                imm_finebusinesses, imm_bansyrianrefugees, imm_moreworkvisas, imm_deport, imm_muslimban, abortion_always, abortion_20wkban,
                abortion_rapeincesthealth, abortion_noinsurance, abortion_hyde, abortion_never, env_co2reg, env_35mpg, env_renewablereq,
                env_cleanacts, crime_nomindrugsentences, crime_bodycameras, crime_morepolice, crime_longersentences, gay_marriage,
                ideology_self, ideology_governor, ideology_obama, ideology_clinton, ideology_trump, ideology_garland, ideology_democrats,
                ideology_republicans, ideology_scotus, ideology_senator_1, ideology_senator_2, ideology_senate_cand1, ideology_senate_cand2,
                ideology_house_cand1, ideology_house_cand2, ideology_rep, support_garland, support_tpp, support_freedomact, support_taa,
                support_nclbrepeal, support_infrastructure, support_iransanctions, support_capitatedmedicare, support_acarepeal, 
                support_12minwage, partyreg, plan_to_vote, early_pres_vote, pres_preference, senate_preference, governor_preference, 
                house_preference, votereg_post, voted_2016_post, reason_didnt_vote_post, reason_didnt_vote_second_post, vote_method_post,
                vote_location_post, vote_wait_time_post, same_day_reg_post, voter_reg_problem_post, vote_problem_id_post, vote_problem_reg_post,
                vote_problem_place_post, vote_problem_other_post, vote_allowed_post, vote_intimidated_post, pres_vote_2016_post, 
                pres_nonvoter_pref_2016_post, senate_vote_2016_post, governor_vote_2016_post, house_vote_2016_post, ag_vote_2016_post, 
                sos_vote_2016_post, state_senate_vote_2016_post, state_house_vote_2016_post, mil_secureoil_post, mil_destroycamp_post,
                mil_genocidecivilwar_post, mil_spreaddemocracy_post, mil_protectallies_post, mil_helpun_post, pastyear_attendmeeting_post,
                pastyear_politicalsign_post, pastyear_workcampaign_post, pastyear_politicaldonation_post, pastyear_blooddonation_post,
                donated_pres_post, donated_senate_homestate_post, donated_senate_otherstate_post, donated_house_homestate_post,
                donated_house_otherstate_post, donated_state_candidate_post, donated_party_post, donated_workpac_post, donated_nonworkpac_post,
                donated_other_post, donation_total = CC16_417c, contrib_influencepolicy_post, contrib_helpbusiness_post, contrib_network_post,
                contrib_candidatesonly_post, contrib_civicduty_post, contacted_by_org_post, contact_inperson_post, contact_phone_post,
                contact_emailtext_post, contact_mail_post = contact_mail, ever_run_post, ever_run_schoolboard_post, ever_run_localboard_post,
                ever_run_citycouncil_post, ever_run_mayor_post, ever_run_da_post, ever_run_county_post, ever_run_stateleg_post, 
                ever_run_state_post, ever_run_federal_post, ever_run_judge_post, ever_run_other_post, pid3_post, demstrength_post, 
                repstrength_post, indlean_post, racism_angry_post, racism_whiteprivilege_post, racism_fear_post, racism_isolatedincidents_post,
                know_housecand1_race_post, know_housecand2_race_post, know_rep_race_post, state_spending_welfare_post, 
                state_spending_healthcare_post, state_spending_education_post, state_spending_law_post, state_spending_infrastructure_post,
                community_grade_schools_post, community_grade_police_post, community_grade_road_post, community_grade_zoning_post,
                community_grade_mayor_post, community_grade_council_post)

write_csv(cces_2016_full, "CCES/data/2016/cces_2016_full.csv")

cces_2016_full %>%
  dplyr::select(id, weight = commonweight_vv_post, weight_lgbt = commonweight_vv_lgbt, state, county = countyname_post, zip, cd = cdid115_post,
                gender, sexuality, trans, birthyr, educ, race, parent = child18, faminc, marstat, union, unionhh, pid3 = pid3_post, pid7, 
                ideology = ideo5, partyreg, church_attendance = pew_churatd, born_again = pew_bornagain, religion = religpew, ownstocks = investor,
                approve_obama, approve_congress, approve_scotus, pres_vote_2012, voted_2016_primary, primary_vote_2016, 
                pres_vote_2016 = pres_vote_2016_post, senate_vote_2016 = senate_vote_2016_post, house_vote_2016 = house_vote_2016_post, 
                governor_vote_2016 = governor_vote_2016_post, imm_amnesty, imm_moresecurity, imm_dream, imm_finebusinesses, imm_bansyrianrefugees, 
                imm_moreworkvisas, imm_deport, imm_muslimban, abortion_always, abortion_20wkban, abortion_rapeincesthealth, abortion_noinsurance, 
                abortion_hyde, abortion_never, env_co2reg, env_35mpg, env_renewablereq, env_cleanacts, crime_nomindrugsentences, crime_bodycameras,
                crime_morepolice, crime_longersentences, gay_marriage, guns_backgroundchecks, guns_prohibitregistry, guns_assaultban, 
                guns_concealed, isis_stayout, isis_sendhumaid, isis_sendmilaid, isis_nofly, isis_airstrikes, isis_sendadvisors, isis_sendtroops, 
                support_garland, support_tpp, support_freedomact, support_taa, support_nclbrepeal, support_infrastructure, support_iransanctions, 
                support_capitatedmedicare, support_acarepeal, support_12minwage, mil_secureoil = mil_secureoil_post, 
                mil_destroycamp = mil_destroycamp_post, mil_genocidecivilwar = mil_genocidecivilwar_post, 
                mil_spreaddemocracy = mil_spreaddemocracy_post, mil_protectallies = mil_protectallies_post, mil_helpun = mil_helpun_post, 
                racism_angry = racism_angry_post, racism_whiteprivilege = racism_whiteprivilege_post, racism_fear = racism_fear_post, 
                racism_isolatedincidents = racism_isolatedincidents_post) %>%
  write_csv("CCES/data/2016/cces_2016_abridged.csv")
